name: build

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build.yml'

jobs:
  go-build:
    name: Go Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - linux
          - darwin
          - windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Go build
        run: go build
        env:
          GOOS: ${{ matrix.os }}
